### PR TITLE
Bleed through between tests

### PR DESCRIPTION
**Pull request by jlward**
With transaction test case mostly.

https://gist.github.com/jlward/4d21b85f49ec4a9acd43

### CODE REVIEW

**Comment by winhamwr** [comment]
What should we do regarding this and #34? Looks like they share some of the same code.

**Comment by jlward** [comment]
I don't think this is needed anymore. Since on master the problem was fixed.

**Comment by winhamwr** [comment]
I reproduced PolicyStat's full mixin and custom client test structure and I have a fairly minimal testcase, now. The bleedthrough problem is not actually fixed, but now that I can reproduce it, it's definitely fixable.

**Comment by winhamwr** [comment]
Woohoo!

**Pull request merged**
